Controllers/CountryController.cs
using IdentityMovie.Areas.Identity.Data;
using IdentityMovie.Interface;
/*using IdentityMovie.Migrations;*/
using IdentityMovie.Models;
using IdentityMovie.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;

namespace IdentityMovie.Controllers
{
    public class CountryController : Controller
    {
        private readonly ICountryRepository _countryRepository;
        public CountryController(ICountryRepository countryRepository)
        {
            _countryRepository = countryRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<Country> countries = _countryRepository.GetAllCountries();
            return View(countries);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Country country)
        {
            if (ModelState.IsValid)
            {
                _countryRepository.AddCountry(country);
                TempData["SuccessMessages"] = "Country created sucessfully!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["ErrorMessages"] = "Model state is invalid";
                return View();
            }
            
        }

        [HttpGet]
        public IActionResult Update()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Update(Country country)
        {
            _countryRepository.UpdateCountry(country);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(Country country)
        {
           _countryRepository.DeleteCountry(country);
            return RedirectToAction("Index");
        }
    }
}

Controllers/GenreController.cs
using IdentityMovie.Areas.Identity.Data;
using IdentityMovie.Interface;
using IdentityMovie.Models;
using IdentityMovie.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Runtime.CompilerServices;

namespace IdentityMovie.Controllers
{
    public class GenreController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly IGenreRepository _genreRepository;
        
        public GenreController(ApplicationDbContext dbContext, IGenreRepository genreRepository)
        {
            _dbContext = dbContext;
            _genreRepository = genreRepository; 
        }

        public IActionResult Index()
        {
            var getlist = _dbContext.Genres.ToList();
            return View(getlist);
        }

        [HttpGet]
        public  List<Genre> GetAll()
        {
            var genres =  _dbContext.Genres.ToList();
            return genres;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Genre genre)
        {
            var add = _genreRepository.AddGenre(genre);
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Update()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Update(Genre genre)
        {
            var edit = _genreRepository.UpdateGenre(genre);
            return RedirectToAction("Index");
        }

        //[HttpGet]
        //public IActionResult Delete(int id)
        //{
        //    var findid = _dbContext.Genres.Find(id);
        //    return View(findid);
        //}


        [HttpGet]
        public IActionResult Delete(Genre genre)
        {
            var remove = _genreRepository.DeleteGenre(genre.Id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/MovieController.cs
using IdentityMovie.Areas.Identity.Data;
using IdentityMovie.Interface;
using IdentityMovie.Models;
using IdentityMovie.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
//using IdentityMovie.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Xml.Linq;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace IdentityMovie.Controllers
{
    [Authorize(Roles ="Admin,User")]
    public class MovieController : Controller
    {
        //Initializing Required Repositories
        public readonly IMovieRepository _movieRepository;
        public readonly IYearRepository _yearRepository;
        public readonly ICountryRepository _countryRepository;
        public readonly IGenreRepository _genreRepository;
        public readonly ICommentRepository _commentRepository;
        public readonly IWebHostEnvironment _webHostEnvironment; //used for serving static file in specific directories 

        public MovieController(IMovieRepository movieRepository, ICountryRepository countryRepository, IYearRepository yearRepository, IGenreRepository genreRepository, ICommentRepository commentRepository, IWebHostEnvironment webHostEnvironment )
        {
            _movieRepository = movieRepository;
            _yearRepository = yearRepository;
            _countryRepository = countryRepository;
            _genreRepository = genreRepository;
            _commentRepository = commentRepository;
            _webHostEnvironment = webHostEnvironment;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var getlist = _movieRepository.SpGetAllMovies();
            return View(getlist);
        }


        [HttpGet]
        public IActionResult Create()
        {
           
            var yearlist = new SelectList (_yearRepository.GetAllYears(), "Id", "Years");
            ViewData["YearId"] = yearlist;

            var genrelist = new SelectList (_genreRepository.GetAllGenres(), "Id", "GenreName");
            ViewData["GenreId"] = genrelist;

            var countrylist = new SelectList (_countryRepository.GetAllCountries(), "Id", "Name");
            ViewData["CountryId"] = countrylist;

            return View();
           
        }

        [HttpPost]
        public IActionResult Create(CreateMovieVM movie)
        {
            var path = _webHostEnvironment.WebRootPath;
            var filePath = "Movie/CoverPhoto/" + movie.MovieId + movie.ImagePath.FileName;
            var fullPath = Path.Combine(path, filePath);
            UploadFile(movie.ImagePath, fullPath);
            var newmovie = new Movie()
            {
                Title = movie.Title,
                Description = movie.Description,
                GenreId = movie.GenreId,
                YearId = movie.YearId,
                CountryId = movie.CountryId,
                Photo = filePath
            };
            _movieRepository.AddMovie(newmovie);
            TempData["SuccessMessages"] = "Movie created sucessfully!";
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Update(int id)
        {

            var yearlist = new SelectList(_yearRepository.GetAllYears(), "Id", "Years");
            ViewData["YearId"] = yearlist;

            var genrelist = new SelectList(_genreRepository.GetAllGenres(), "Id", "GenreName");
            ViewData["GenreId"] = genrelist;

            var countrylist = new SelectList(_countryRepository.GetAllCountries(), "Id", "Name");
            ViewData["CountryId"] = countrylist;

            var movie = _movieRepository.GetById(id);

            return View(movie);
        }

        [HttpPost]
        public IActionResult Update(Movie movie)
        {
            /*var image = Request.Form.Files.FirstOrDefault();
            var fileName = Guid.NewGuid().ToString();
            var path = $@"Movies\";
            var wwwRootPath = _webHostEnvironment.WebRootPath;
            var uploads = Path.Combine(wwwRootPath, path);
            var extension = Path.GetExtension(image.FileName);
            var x = Path.Combine(uploads, fileName + extension);
            using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
            {
                image.CopyTo(fileStreams);
            }
            movie.Photo = $"\\Movies\\{fileName}" + extension;*/
            var edit = _movieRepository.UpdateMovie(movie);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Delete(int id)
        {
            var remove = _movieRepository.DeleteMovie(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Details(int id)
        
       {
            Movie movie = _movieRepository.GetById(id);
            List<CommentVM> comments = _commentRepository.GetComments(id);
            Year yearList = _yearRepository.GetYearById(movie.YearId);
            Genre GenreList = _genreRepository.GetGenreById(movie.GenreId);
            Country CountryList = _countryRepository.GetCountryById(movie.CountryId);
            MovieDetailsVM movieDetails = new MovieDetailsVM 
            { 
                Movie = movie,
                Comments = comments,
                Year = yearList,
                Genre = GenreList,
                Country = CountryList
            };
            
        
            return View(movieDetails);
        }

        [HttpPost]
        public IActionResult Details(Movie movie)
        {
            var details = _movieRepository.GetById(movie.MovieId);
            return RedirectToAction("Index");
        }


        public void UploadFile(IFormFile file, string path)
        {
            FileStream stream = new FileStream(path, FileMode.Create);
            file.CopyTo(stream);
        }
    }
}

Controllers/YearController.cs
using IdentityMovie.Areas.Identity.Data;
using IdentityMovie.Interface;
using IdentityMovie.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IdentityMovie.Controllers
{

    public class YearController : Controller
    {

        private readonly ApplicationDbContext _dbContext;
        public readonly IYearRepository _yearRepository;
        public YearController(ApplicationDbContext dbContext, IYearRepository yearRepository)
        {
            _dbContext = dbContext;
            _yearRepository = yearRepository;
        }

        public IActionResult Index()
        {
            var getlist = _dbContext.Years.ToList();
            return View(getlist);
        }

        [HttpGet]
        public List<Year> GetAll()
        {
            var genres = _dbContext.Years.ToList();
            return genres;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Year yearss)
        {
            var add = _yearRepository.AddYear(yearss);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Update(Year yearss)
        {
            var edit = _yearRepository.UpdateYear(yearss);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Delete(Year years)
        {
            var remove = _yearRepository.DeleteYear(years);
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IdentityMovie</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> 
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script> 
    <script src="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css"></script> 
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/IdentityMovie.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/Images/movielogo.jpg"height="50" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="Index">Genre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Country</a>
                        </li>  
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Year" asp-action="Index">Years</a>
                         </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial"/>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - IdentityMovie - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>